import { ModelConfig } from "./types";

export const WORK_MODEL_CONFIGS: ModelConfig[] = [
	{
		id: "python",
		type: "svg",
		svgPath: "/models/python.svg",
		scale: 0.0045,
		depth: 100,
		preserveColors: false,
		randomizeColor: false,
		hoverText: "Multidisciplinary Python expertise",
	},
	{
		id: "gitlab",
		type: "svg",
		svgPath: "/models/gitlab.svg",
		scale: 0.005,
		depth: 40,
		preserveColors: true,
		randomizeColor: false,
		hoverText: "Configure CI/CD with GitLab",
	},
	{
		id: "aws",
		type: "svg",
		svgPath: "/models/aws.svg",
		scale: 0.004,
		depth: 50,
		preserveColors: true,
		randomizeColor: false,
		hoverText: "AWS Certified Solutions Architect",
	},
	{
		id: "gcp",
		type: "svg",
		svgPath: "/models/gcp.svg",
		scale: 0.0005,
		depth: 250,
		preserveColors: true,
		randomizeColor: false,
		hoverText: "Create on Google Cloud Platform",
	},
	{
		id: "react",
		type: "svg",
		svgPath: "/models/react.svg",
		scale: 0.04,
		depth: 4,
		preserveColors: true,
		randomizeColor: false,
		hoverText: "Develop web experiences with React",
	},
	{
		id: "terraform",
		type: "svg",
		svgPath: "/models/terraform.svg",
		scale: 0.04,
		depth: 7.5,
		preserveColors: true,
		randomizeColor: false,
		hoverText: "Manage infrastructure with Terraform",
	},
	{
		id: "typescript",
		type: "svg",
		svgPath: "/models/typescript.svg",
		scale: 0.0016,
		depth: 150,
		preserveColors: true,
		randomizeColor: false,
		hoverText: "Contribute to TypeScript codebases",
	},
	{
		id: "docker",
		type: "svg",
		svgPath: "/models/docker.svg",
		scale: 0.04,
		depth: 10,
		preserveColors: true,
		randomizeColor: false,
		hoverText: "Containerize apps with Docker",
	},
	{
		id: "brain",
		type: "obj",
		path: "/models/brain.obj",
		scale: 0.00275,
		randomizeColor: false,
		hoverText: "Productionize AI workflows",
		color: "#FF91AF",
		collider: "ball",
		hullApproximation: 0.001,
	},
	{
		id: "books",
		type: "glb",
		glbPath: "/models/books.glb",
		scale: 0.85,
		randomizeColor: false,
		hoverText: "Education in Stats, Econ, & CS",
	},
	// {
	// 	id: "hallway",
	// 	type: "svg",
	// 	svgPath: "/models/hallway.svg",
	// 	scale: 0.04,
	// 	depth: 10,
	// 	preserveColors: true,
	// 	randomizeColor: false,
	// 	hoverText: "Building AI characters at Hallway",
	// },
];

export const PERSONAL_MODEL_CONFIGS: ModelConfig[] = [
	{
		id: "california",
		type: "svg",
		svgPath: "/models/ca.svg",
		scale: 0.002,
		depth: 100,
		randomizeColor: true,
		hoverText: "From the Bay Area, CA",
	},
	{
		id: "newyork",
		type: "svg",
		svgPath: "/models/ny.svg",
		scale: 0.002,
		depth: 100,
		randomizeColor: true,
		hoverText: "Live in Brooklyn, NY",
	},
	{
		id: "earth",
		type: "glb",
		glbPath: "/models/earth.glb",
		scale: 0.5,
		randomizeColor: false,
		hoverText: "Seasoned traveler",
		collider: "ball",
	},
	{
		id: "lionandsun",
		type: "svg",
		svgPath: "/models/lionandsun.svg",
		scale: 0.006,
		depth: 30,
		preserveColors: true,
		randomizeColor: false,
		hoverText: "Iranian heritage",
	},
	{
		id: "glossa",
		type: "text",
		text: "γλώσσα",
		scale: 0.3,
		randomizeColor: false,
		hoverText: "Linguistics enthusiast",
	},
	{
		id: "guitar",
		type: "glb",
		glbPath: "/models/guitar.glb",
		scale: 0.45,
		randomizeColor: false,
		hoverText: "Sonic explorer",
		collider: "hull",
		hullApproximation: 0.01,
	},
	{
		id: "column",
		type: "glb",
		glbPath: "/models/column.glb",
		scale: 0.75,
		randomizeColor: false,
		hoverText: "History lover",
	},
	{
		id: "dumbell",
		type: "glb",
		glbPath: "/models/dumbell.glb",
		scale: 0.25,
		randomizeColor: false,
		hoverText: "Athlete",
		collider: "hull",
		hullApproximation: 0.01,
	},
	{
		id: "knight",
		type: "glb",
		glbPath: "/models/knight.glb",
		scale: 0.2,
		randomizeColor: false,
		hoverText: "Strategy gamer",
		collider: "hull",
		hullApproximation: 0.01,
	},
];
