import { ModelConfig } from "./types";

export const MODEL_CONFIGS: ModelConfig[] = [
	{
		id: "california",
		type: "obj",
		path: "/models/california.obj",
		scale: 0.4,
		randomizeColor: true,
	},
	{
		id: "newyork",
		type: "obj",
		path: "/models/newyork.obj",
		scale: 0.4,
		randomizeColor: true,
	},
	{
		id: "python",
		type: "svg",
		svgPath: "/models/python.svg",
		scale: 0.005,
		depth: 20,
		preserveColors: false,
		randomizeColor: false,
	},
	{
		id: "gitlab",
		type: "svg",
		svgPath: "/models/gitlab.svg",
		scale: 0.005,
		depth: 40,
		preserveColors: true,
		randomizeColor: false,
	},
	{
		id: "aws",
		type: "svg",
		svgPath: "/models/aws.svg",
		scale: 0.004,
		depth: 25,
		preserveColors: true,
		randomizeColor: false,
	},
	{
		id: "gcp",
		type: "svg",
		svgPath: "/models/gcp.svg",
		scale: 0.0006,
		depth: 100,
		preserveColors: true,
		randomizeColor: false,
	},
	{
		id: "react",
		type: "svg",
		svgPath: "/models/react.svg",
		scale: 0.04,
		depth: 2,
		preserveColors: true,
		randomizeColor: false,
	},
	{
		id: "terraform",
		type: "svg",
		svgPath: "/models/terraform.svg",
		scale: 0.05,
		depth: 2,
		preserveColors: true,
		randomizeColor: false,
	},
	{
		id: "typescript",
		type: "svg",
		svgPath: "/models/typescript.svg",
		scale: 0.0016,
		depth: 75,
		preserveColors: true,
		randomizeColor: false,
	},
];
