import { ModelConfig } from "./types";

export const WORK_MODEL_CONFIGS: ModelConfig[] = [
	{
		id: "python",
		type: "svg",
		svgPath: "/models/python.svg",
		scale: 0.005,
		depth: 20,
		preserveColors: false,
		randomizeColor: false,
		hoverText: "Multidisciplinary Python expertise",
	},
	{
		id: "gitlab",
		type: "svg",
		svgPath: "/models/gitlab.svg",
		scale: 0.005,
		depth: 40,
		preserveColors: true,
		randomizeColor: false,
		hoverText: "Configure CI/CD with GitLab",
	},
	{
		id: "aws",
		type: "svg",
		svgPath: "/models/aws.svg",
		scale: 0.004,
		depth: 25,
		preserveColors: true,
		randomizeColor: false,
		hoverText: "AWS Certified Solutions Architect",
	},
	{
		id: "gcp",
		type: "svg",
		svgPath: "/models/gcp.svg",
		scale: 0.0005,
		depth: 150,
		preserveColors: true,
		randomizeColor: false,
		hoverText: "Create on Google Cloud Platform",
	},
	{
		id: "react",
		type: "svg",
		svgPath: "/models/react.svg",
		scale: 0.04,
		depth: 2,
		preserveColors: true,
		randomizeColor: false,
		hoverText: "Develop web experiences with React",
	},
	{
		id: "terraform",
		type: "svg",
		svgPath: "/models/terraform.svg",
		scale: 0.05,
		depth: 2,
		preserveColors: true,
		randomizeColor: false,
		hoverText: "Manage infrastructure with Terraform",
	},
	{
		id: "typescript",
		type: "svg",
		svgPath: "/models/typescript.svg",
		scale: 0.0016,
		depth: 75,
		preserveColors: true,
		randomizeColor: false,
		hoverText: "Contribute to TypeScript codebaes",
	},
	{
		id: "docker",
		type: "svg",
		svgPath: "/models/docker.svg",
		scale: 0.04,
		depth: 2.5,
		preserveColors: true,
		randomizeColor: false,
		hoverText: "Containerize with Docker",
	},
	{
		id: "brain",
		type: "obj",
		path: "/models/brain.obj",
		scale: 0.0025,
		randomizeColor: false,
		hoverText: "Build AI systems",
		color: "#FF91AF",
	},
	{
		id: "book",
		type: "glb",
		glbPath: "/models/book.glb",
		scale: 0.45,
		randomizeColor: false,
		hoverText: "Education in Stats, Econ, & CS",
	},
];

export const PERSONAL_MODEL_CONFIGS: ModelConfig[] = [
	{
		id: "california",
		type: "svg",
		svgPath: "/models/ca.svg",
		scale: 0.002,
		depth: 100,
		randomizeColor: true,
		hoverText: "From the Bay Area, CA",
	},
	{
		id: "newyork",
		type: "svg",
		svgPath: "/models/ny.svg",
		scale: 0.002,
		depth: 100,
		randomizeColor: true,
		hoverText: "Live in Brooklyn, NY",
	},
	{
		id: "globe",
		type: "glb",
		glbPath: "/models/globe.glb",
		scale: 2.5,
		randomizeColor: false,
		hoverText: "Traveled while working for 3 years",
	},
	{
		id: "lionandsun",
		type: "svg",
		svgPath: "/models/lionandsun.svg",
		scale: 0.006,
		depth: 30,
		preserveColors: true,
		randomizeColor: false,
		hoverText: "Iranian heritage",
	},
	{
		id: "glossa",
		type: "text",
		text: "γλώσσα",
		scale: 0.3,
		randomizeColor: false,
		hoverText: "Linguistics enthusiast",
	},
	// {
	// 	id: "guitar",
	// 	type: "glb",
	// 	glbPath: "/models/guitar.glb",
	// 	scale: 0.2,
	// 	randomizeColor: false,
	// 	hoverText: "Sonic explorer",
	// },
	{
		id: "column",
		type: "glb",
		glbPath: "/models/column.glb",
		scale: 0.75,
		randomizeColor: false,
		hoverText: "History lover",
	},
	{
		id: "motorcycle",
		type: "glb",
		glbPath: "/models/motorcycle.glb",
		scale: 0.1,
		randomizeColor: false,
		hoverText: "Explorer by nature",
	},
];
